spring.application.name=demo

# Info
management.info.env.enabled=true
info.app.name=demo
info.app.version=1.0.0
info.app.description=Demo application
info.app.author=John Doe
info.app.email=john.doe@example.com
info.app.website=https://www.example.com

# Security
management.endpoints.web.exposure.include=health,info
management.endpoints.web.exposure.exclude=beans
spring.security.user.name=adminloco

# Custom Properties
dog.name=Owlyn
cat.name=Ojitos

# Stuff
spring.main.lazy-initialization=true
